# Generated by Django 3.2.3 on 2021-05-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210517_0221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
