# Generated by Django 3.2.3 on 2021-05-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='course',
        ),
    ]
