# Generated by Django 3.2.3 on 2021-05-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
