# Generated by Django 3.2.3 on 2021-05-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_on']},
        ),
    ]
